flask_app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class SurveyResponse(db.Model):
    id = db.Column(db.Integer, primary_key=True) # Integer
    age = db.Column(db.String(100), nullable=False) # String
    country = db.Column(db.String(100), nullable=False) # String
    gender = db.Column(db.String(20), nullable=False) # String
    watch_olympics = db.Column(db.String(20), nullable=False) # String
    summer_vs_winter = db.Column(db.String(20), nullable=False) # String
    athlete = db.Column(db.String(20), nullable=False)# String
    sport = db.Column(db.String(20), nullable=False) # String
    how_long = db.Column(db.Integer) # Integer
    become_olympian = db.Column(db.Boolean) # Boolean

    def __repr__(self):
        return f"Age : {self.age}, Gender: {self.gender}"

flask_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from .models import db
from .routes import main
from .config import Config

migrate = Migrate()

def create_app():
    app = Flask(__name__)

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///surveys.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False


 
    db.init_app(app)
    migrate.init_app(app, db)
    with app.app_context():
        db.create_all()

    
    app.register_blueprint(main)
    
    return app

flask_app/routes.py
from flask import Blueprint, render_template, redirect , request, jsonify
from .data import countries, sports
from .models import db, SurveyResponse
main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('index.html')

@main.route('/recommendations')
def recommendations():
    return render_template('recommendations.html')


@main.route('/survey')
def survey():
    return render_template('survey.html', countries=countries, sports=sports)

@main.route('/survey_submitted')
def survey_submitted():
    return render_template('survey_submitted.html')

@main.route('/submit', methods=['POST'])
def submit():
    if request.method == 'POST':
        become_olympian = request.form.get("become_Olympian", "false")  # Default to "false"
        become_olympian = become_olympian.lower() == "true" 
        new_entry = SurveyResponse(
            age= request.form['age'],
            country= request.form['country'],
            gender= request.form['gender'],
            watch_olympics= request.form['watch_olympics'],
            summer_vs_winter= request.form['summer_vs_winter'],
            athlete= request.form['athlete'],
            sport= request.form['sport'],
            how_long = request.form['how_long'],
            become_olympian= become_olympian
        )

        db.session.add(new_entry)
        db.session.commit()
        return redirect('/survey_submitted')
 

    else:
        render_template('survey.html')

@main.route("/print_db", methods=["GET"])
def print_db():
    entrys = SurveyResponse.query.all()
    entrys_list = [{"id": entry.id, "age": entry.age, "country": entry.country} for entry in entrys]
    return jsonify(entrys_list)

flask_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Flask-Dash App{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <header>
        <h1>Olympic Games Analysis</h1>
    </header>
    <main>
        {% block content %}
        {% endblock %}
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    </main>
</body>
</html>

flask_app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="main">
    <img src="{{ url_for('static', filename='images/1140-london-olympics.jpg') }}" >
    <ul class="home_list">
        <li class="home_list">
            <a href="/main_dashboard">Main Dashboard</a>
        </li>
        <li class="home_list">
            <a href="/survey">Survey</a>
        </li>
        <li class="home_list">
            <a href="/survey_dashboard">Survey Dashboard</a>
        </li>
        <li class="home_list">
            <a href="/recommendations">Recommendations</a>
        </li>
        
    </ul>
</div>
{% endblock %}

flask_app/templates/recommendations.html
{% extends 'base.html' %}

{% block content %}
<div class="reccomendations">
    <h1>Recommendations</h1>
    <li class="home_list"><a href="/">Home</a></li>
    <img class="rec_img" src="{{ url_for('static', filename='images/133149.jpg') }}">

    <h2>1. Sports Development</h2>
    <p>
        From my exploration of the most successful countries in the Olympics it has become very clear that
        the GDP of a country has a huge impact on whether a country succeeds or not. Countries such as the USA, Russia and China dominate
        while smaller nations or less developed countries such as much of Africa have little or no medals at all.
    </p>
    <img class="rec_img" src="{{ url_for('static', filename='images/medals_countrys.png') }}">
    <h3>
        Recommendations:
    </h3>
    <ul>
        <li class="rec_li">Develop grassroots programs in
            underrepresented countries to broaden competition</li>
        <li class="rec_li">Foster partnerships between established sports nations and developing ones to exchange expertise</li>
    </ul>

    <img class="rec_img" src="{{ url_for('static', filename='images/shoes_four_running_kenya_youth_sports_development-960x510.webp') }}">
    
    <h2>2. Gender Equality</h2>
    <p>
        Gender inequality is extremely prevalent within the Olympic's history. It was only in 1900 that women were allowed to compete in the
        games and it was only in the London games 2012 that every country competing had a women on their team.
        However it is evident from my analysis that the olympics is becoming much more equal in terms of gender although true equality has not
        yet been reached. (In the 2024 games there were equal medals for both men and women however my chosen dataset does not surpass 2016)
    </p>
    <img class="rec_img" src="{{ url_for('static', filename='images/gender_distribution.png') }}">
    <h3>
        Recommendations:
    </h3>
    <ul>
        <li class="rec_li">Ensure equal medal events for men and women in all sports</li>
        <li class="rec_li">Encourage participation from underrepresented genders by promoting campaigns and increasing funding.</li>
    </ul>
  
    <img class="rec_img" src="{{ url_for('static', filename='images/fu0iezzhvk0edgyv6rob.avif') }}">
    <h2>3. Introduction of new sports</h2>
    <p>Throughout olympic history the sports included have grown and changed. This is done in order to keep the games
        fresh and exiting while also appealing to younger audiences. In the LA games 2028 Baseball, Softball, Cricket, Lacrosse, Squash and Flag football will all be added to the schedule.
    </p>
    <img class="rec_img" src="{{ url_for('static', filename='images/LA28-NewOlympicSportProposal_1920x1080_WEB1.jpg') }}">
    <h3>
        Recommendations:
    </h3>
    <ul>
        <li class="rec_li">Continuously review and adapt the Olympic program to reflect evolving global interests</li>
        <li class="rec_li">Consider more regional sports to attract diverse participation</li>
    </ul>
    <h2>4. Environmental Sustainability</h2>
    <p>
        The Olympics is probably the biggest sporting event on the planet. It attracts millions of tourists and costs billions to
        run. It also has a huge impact on the environment releasing millions of tons of Carbon Dioxide into the atmosphere every 4 years.
        A recent change has occurred lately however as The International Olympic Committee has pledged to make the games as green as possible.
    </p>
    <img class="rec_img" src="{{ url_for('static', filename='images/1722531797257.png') }}">
    <h3>
        Recommendations:
    </h3>
    <ul>
        <li class="rec_li">Avail of already existing infrastructure and stadiums instead of building everything from scratch</li>
        <li class="rec_li">Ensure that any venues or infrastructure created for the games have a purpose after the games conclude</li>
        <li class="rec_li">Use Venues that are closer to each-other or are accessible by public transport</li>
        <li class="rec_li">Remove the use of single use plastics in venues</li>
    </ul>

    <h2>5.Historical legacy and global collaboration</h2>
    <p>The Olympics throughout history has always been an event that
        has shown the best of humanity. It is a place where every nation
        is equal and where political rivalries have been put aside. The Olympics have
        inspired younger generations throughout the years, promoting health, fitness and sport
        as well as fostering the next generation of athletes. The Games have also put on show many unique and 
        diverse cultures throughout the world displaying the best best that humanity have to offer.
    
        
    </p>
    <img class="rec_img" src="{{ url_for('static', filename='images/INTE_52469_619568.jpg') }}">
    <h3>
        Recommendations:
    </h3>
    <ul>
        <li class="rec_li">Use the games as a platform to promote peacebuilding</li>
        <li class="rec_li">Highlight stories of resilience, inclusivity, and shared humanity through the Games </li>
        <li class="rec_li">Use the games as a means to share cultures and traditions</li>
    </ul>
    <img class="rec_img" src="{{ url_for('static', filename='images/674f1a57a0e8a8001d75f3f5.jpg') }}">
    <br>
</div>
{% endblock %}

flask_app/templates/survey.html
{% extends 'base.html' %}

{% block content %}


<div class="survey"> 
    <li class="home_list"><a href="/">Home</a></li>
    <form id="survey_form" name="survey_form" method="POST" action="{{ url_for('main.submit') }}">
        <h2>Take this Olympic Games Survey!</h2>
        <label for="age">Age</label>
        <select name="age" id="age" class="dropdown">
            <option value="" disabled selected>What is your age group?</option>
            <option value="under_18">Under 18</option>
            <option value="18-24">18-24</option>
            <option value="25-34">25-34</option>
            <option value="35-44">35-44</option>
            <option value="45-54">45-54</option>
            <option value="55+">55+</option>
        </select>
        <p class="error-message"></p>
       
        
        <label for="country">Country</label>
        <select name="country" id="country" class="dropdown">
            <option value="" disabled selected>Select your Country</option>
            {% for country in countries %}
                <option value="{{ country }}">{{ country }}</option>
            {% endfor %}
        </select>
        <p class="error-message"></p>
        

        <label for="gender">Gender</label>
        <select name="gender" id="gender" class="dropdown">
            <option value="" disabled selected>Select your Gender</option>
            <option value="male">Male</option>
            <option value="female">Female</option>
            <option value="other">Other</option>
        </select>
        <p class="error-message"></p>
        


        <label for="watch_olympics">How often do you watch the Olympics?</label>
        <select name="watch_olympics" id="watch_olympics" class="dropdown">
            <option value="" disabled selected>How much?</option>
            <option value="every_olympics">Every Olympics</option>
            <option value="occasionally">Occasionally</option>
            <option value="rarely">Rarely</option>
            <option value="never">Never</option>
        </select>
        <p class="error-message"></p>
        

        <label for="how_long">How long have you been watching the Olympics? (0-100 years)</label>
        <input type="text" id="how_long" name="how_long" class="text_input">
        <p id="number_error" style="color: #fe53bb;"></p>
        
        <label for="summer_vs_winter">Which do you prefer?</label>
        <select name="summer_vs_winter" id="summer_vs_winter" class="dropdown">
            <option value="" disabled selected>Which?</option>
            <option value="summer">Summer</option>
            <option value="winter">Winter</option>
        </select>
        <p class="error-message"></p>
        

        <label for="sport">Favourite Sport</label>
        <select name="sport" id="sport" class="dropdown">
            <option value="" disabled selected>Select your favourite Sport</option>
            {% for sport in sports %}
                <option value="{{ sport }}">{{ sport }}</option>
            {% endfor %}
        </select>
        <p class="error-message"></p>
     

        <label for="athlete">Favourite athlete</label>
        <input type="text" id="athlete" name="athlete" class="text_input">
        <p class="error-message"></p>
        

        <label for="follow_olympics">How do you follow the olympics?</label>
        <select name="follow" id="follow" class="dropdown">
            <option value="" disabled selected>How do you follow the olympics?</option>
            <option value="tv">TV</option>
            <option value="social_media">Social Media</option>
            <option value="tv">TV</option>
            <option value="news">News Websites</option>
            <option value="in_person">In Person</option>
            <option value="other">Other</option>
        </select>
        <p class="error-message"></p>
        

        <label for="become_Olympian">Do you wish you could become and Olympian?</label>
        <input type="checkbox" name="become_Olympian"  id="become_Olympian" class="checkbox" value="true"></input>
        <p class="error-message"></p>
      

        <button type="submit" onclick="check_how_long()">Submit</button>
    </form>
    <p id="validation"></p>
    <div id="message"></div>
</div>

{% endblock %}

flask_app/templates/survey_submitted.html
{% extends 'base.html' %}

{% block content %}

<div class="survey_submitted">
    <h2>Thank You for completing the Survey!</h2>
    <ul class="sur_list">
        <li class="sur_list">
            <a href="/survey">Redo the Survey</a>
        </li>
        <li class="sur_list">
            <a href="/survey_dashboard">View Results</a>
        </li>
        <li class="sur_list">
            <a href="/">Go Home</a>
        </li>
        
    </ul>
</div>
{% endblock %}